name: Cache and Install APT Packages
description: Caches APT packages to speed up subsequent installations in GitHub Actions workflows.
author: David C. Manuelda
email: StormByte@gmail.com
branding:
  icon: 'hard-drive'
  color: 'green'

inputs:
  packages:
    description: 'A space-separated list of APT packages to install and cache.'
    required: true
    default: ''
  cache-key:
    description: 'A unique key to identify the cache. Change this key to invalidate the cache.'
    required: false
    default: 'apt-packages-cache'

runs:
  using: "composite"
  steps:
    - name: Cache APT packages
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: ${{ inputs.packages }}
        version: ${{ inputs.cache-key }}
    - name: Install APT packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.packages }}

    - name: Install Chocolatey packages
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install ${{ inputs.packages }} -y