name: Cache and Install APT Packages
description: Caches APT packages deterministically to avoid collisions.
author: David C. Manuelda
branding:
  icon: 'hard-drive'
  color: 'green'

inputs:
  packages:
    description: "Space-separated list of APT packages to install."
    required: true

  cache-key:
    description: "Prefix for the cache key. If empty, caching is disabled."
    required: false
    default: ""

  unique:
    description: >
      If true (default), the cache-key is assumed to be globally unique and
      no hash suffix will be added. If false, a deterministic hash based on
      the package list will be appended to avoid collisions.
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    ###########################################################################
    # 0. COMPUTE DETERMINISTIC HASH (ONLY IF unique == false)
    ###########################################################################
    - name: Compute APT cache key hash
      if: ${{ inputs.cache-key != '' && inputs.unique == 'false' }}
      id: aptkey
      shell: bash
      run: |
        echo "[STEP 0] Computing deterministic cache key hash..."
        HASH=$(echo '${{ inputs.packages }}' | sha256sum | cut -c1-16)
        echo "PACKAGES_HASH=$HASH" >> "$GITHUB_ENV"

    ###########################################################################
    # 1. CREATE CACHE DIRECTORY (UNIQUE OR HASHED)
    ###########################################################################
    - name: Create APT cache directory
      if: ${{ inputs.cache-key != '' }}
      shell: bash
      run: |
        if [ "${{ inputs.unique }}" = "true" ]; then
          # Unique mode: user guarantees the key is globally unique
          CACHE_DIR="$HOME/apt-cache-${{ inputs.cache-key }}"
          echo "[STEP 1] Creating cache directory (unique mode): $CACHE_DIR"
        else
          # Deterministic mode: append hash suffix
          CACHE_DIR="$HOME/apt-cache-${{ inputs.cache-key }}-${PACKAGES_HASH}"
          echo "[STEP 1] Creating cache directory (hashed mode): $CACHE_DIR"
        fi

        echo "CACHE_DIR=$CACHE_DIR" >> "$GITHUB_ENV"
        mkdir -p "$CACHE_DIR"

    ###########################################################################
    # 2. RESTORE CACHE
    ###########################################################################
    - name: Restore APT cache
      if: ${{ inputs.cache-key != '' }}
      id: restore
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_DIR }}
        key: ${{ inputs.unique == 'true'
                && inputs.cache-key
                || format('{0}-{1}', inputs.cache-key, env.PACKAGES_HASH) }}

    ###########################################################################
    # 3. COPY RESTORED CACHE BACK INTO SYSTEM APT CACHE
    ###########################################################################
    - name: Restore cached .deb files into system APT cache
      shell: bash
      run: |
        echo "[STEP 3] Copying restored .deb files into /var/cache/apt/archives..."
        sudo mkdir -p /var/cache/apt/archives
        sudo cp "${CACHE_DIR}"/*.deb /var/cache/apt/archives/ 2>/dev/null || true

    ###########################################################################
    # 4. DOWNLOAD PACKAGES AND DEPENDENCIES (NO INSTALL)
    ###########################################################################
    - name: Download APT packages (dependencies included)
      shell: bash
      run: |
        echo "[STEP 4] Downloading packages and dependencies (no install)..."
        sudo apt-get update
        sudo apt-get install --download-only -y ${{ inputs.packages }}

        echo "[STEP 4] Copying newly downloaded .deb files into cache directory..."
        cp /var/cache/apt/archives/*.deb "${CACHE_DIR}/" 2>/dev/null || true

    ###########################################################################
    # 5. INSTALL PACKAGES USING LOCAL .deb FILES
    ###########################################################################
    - name: Install APT packages
      shell: bash
      run: |
        echo "[STEP 5] Installing packages using local .deb files..."
        sudo apt-get install -y ${{ inputs.packages }}

    ###########################################################################
    # 6. SAVE CACHE (ONLY IF NOT RESTORED)
    ###########################################################################
    - name: Save APT cache
      if: ${{ inputs.cache-key != '' && steps.restore.outputs.cache-hit != 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_DIR }}
        key: ${{ inputs.unique == 'true'
                && inputs.cache-key
                || format('{0}-{1}', inputs.cache-key, env.PACKAGES_HASH) }}
