name: Generate and Deploy Docs

###############################################################################
# 1. WORKFLOW INPUTS
###############################################################################
on:
  workflow_call:
    inputs:
      doc_target:
        required: true
        type: string
        description: "CMake target used to generate the documentation"

      extra-cmake-options:
        required: false
        type: string
        default: ""
        description: "Additional CMake options"

      extra-install:
        required: false
        type: string
        default: ""
        description: "Extra packages to install before building docs"

      docs_source_dir:
        required: false
        type: string
        default: "./docs"
        description: "Directory containing the documentation source"

      docs_output_dir:
        required: false
        type: string
        default: "./_site"

###############################################################################
# 2. CONCURRENCY
###############################################################################
concurrency:
  group: pages
  cancel-in-progress: false

###############################################################################
# 3. JOB: GENERATE DOCUMENTATION
###############################################################################
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Generate documentation
        uses: stormbytepp/githubactions/.github/actions/generate-doc@master
        with:
          doc_target: ${{ inputs.doc_target }}
          extra-cmake-options: ${{ inputs.extra-cmake-options }}
          extra-install: ${{ inputs.extra-install }}
          docs_source_dir: ${{ inputs.docs_source_dir }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.docs_output_dir }}

###############################################################################
# 4. JOB: DEPLOY TO GITHUB PAGES
###############################################################################
  deploy:
    needs: generate-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4